//  Generated list of all register names based on Modbus table.
#ifndef ALL_NAMES_H
#define ALL_NAMES_H
#include <Arduino.h>
#include "Flash/src/Flash.h"
const uint16_t max_name_length = 40; const char all_names[] PROGMEM =
"Action Calib\0"
"Active Energy +\0"
"Active Energy +<10 000\0"
"Active Energy +>10 000\0"
"Active Power +/- : P\0"
"Active Power phase 1 +/- : P1\0"
"Active Power phase 2 +/- : P2\0"
"Active Power phase 3 +/- : P3\0"
"Active Power phase1 +/-\0"
"Active Power phase2 +/-\0"
"Active Power phase3 +/-\0"
"Apparent Power : S\0"
"Apparent Power phase 1 : S1\0"
"Apparent Power phase 2 : S2\0"
"Apparent Power phase 3 : S3\0"
"Apparent Power phase1\0"
"Apparent Power phase2\0"
"Apparent Power phase3\0"
"Clr Relais Impulsion\0"
"Coef Gnrale Courant\0"
"Coef Gnrale Tension\0"
"Current : I1\0"
"Current : I2\0"
"Current : I3\0"
"Current alarm on lower threshold cause:0\0"
"Current alarm on upper threshold cause:0\0"
"Current Transformer primary\0"
"Current Transformer secondary 11A 55A\0"
"Dphasage Phase 1\0"
"Dphasage Phase 2\0"
"Dphasage Phase 3\0"
"Frequency\0"
"Frequency : F\0"
"Frequency : Fr\0"
"Hour Meter\0"
"Hour Meter +<10000\0"
"Hour Meter +>10000\0"
"I 1 AVG MAX\0"
"I 2 AVG MAX\0"
"I 3 AVG MAX\0"
"In AVG MAX\0"
"max/avg active power +\0"
"max/avg apparent power\0"
"Max/avg I1\0"
"Max/avg I2\0"
"Max/avg I3\0"
"Max/avg In\0"
"Max/avg P+\0"
"Max/avg Q+\0"
"max/avg reactive power +\0"
"Max/avg S\0"
"Neutral Current\0"
"Neutral Current : In\0"
"Offset Int/Ext ( default : 0 )\0"
"P+ AVG MAX\0"
"Partial Positive Active Energy: Ea+\0"
"Partial Positive Reactive Energy: Er +\0"
"Phase 1 Current\0"
"Phase 2 Current\0"
"Phase 3 Current\0"
"Phase to Neutral voltage phase 1\0"
"Phase to Neutral voltage phase 2\0"
"Phase to Neutral voltage phase 3\0"
"Phase to Phase Voltage: U12\0"
"Phase to Phase Voltage: U23\0"
"Phase to Phase Voltage: U31\0"
"Power factor : -: capacitif et + : induc\0"
"power factor : -: leadiing et + : laggin\0"
"power factor : -: leading and + : laggin\0"
"Power Factor : -: leading et + : lagging\0"
"Power Factor phase 1 -: leading and + : \0"
"Power factor phase 1 -:leading and +: la\0"
"Power factor phase 1-: leading and +: la\0"
"Power Factor phase 2 -: leading and + : \0"
"Power factor phase 2 -:leading and +: la\0"
"Power factor phase 2-: leading and +: la\0"
"Power Factor phase 3 -: leading and + : \0"
"Power factor phase 3 -:leading and +: la\0"
"Power factor phase 3-: leading and +: la\0"
"Q+ AVG MAX\0"
"Reactive Energy +\0"
"Reactive Energy +>10 000\0"
"Reactive Energy+< 10 000\0"
"Reactive Power +/- : Q\0"
"Reactive Power phase 1 +/- : Q1\0"
"Reactive Power phase 2 +/- : Q2\0"
"Reactive Power phase 3 +/- : Q3\0"
"Reactive Power phase1 +/-\0"
"Reactive Power phase2 +/-\0"
"Reactive Power phase3 +/-\0"
"Set Relais Impul\0"
"Simple voltage : V1\0"
"Simple voltage : V2\0"
"Simple voltage : V3\0"
"TC list :TC 1 / TC2 / TC3 / TC4 / TC5 / \0"
"thd I1\0"
"thd I2\0"
"thd I3\0"
"thd U12\0"
"thd U23\0"
"thd U31\0"
"thd V1\0"
"thd V2\0"
"thd V3\0"
"Total Active Power +/- : P\0"
"Total apparent power : S\0"
"Total Negative Active Energy (no resetab\0"
"Total Positive Active Energy (no resetab\0"
"Total Reactive Power +/- : Q\0"
;

#endif  //  ALL_NAMES_H